---
title: "Fossil-C Profile" 
author: "Hyunmin Kim"
last updated : "`r Sys.Date()`"
output: md_document
knitr:
  opts_chunk:
    echo: false
    warning: false
    message: false
---
## Read Count Summary
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(readr)
library(knitr)
df <- read.table("summary.tsv",header=T)
kable(df, format = "pipe")
```
[tsv download](summary.tsv)


## Barcode and Adapter Structure 

**Design**

```
Xs = i7 index sequence
   i7_5                                     i7_3
5′-CAAGCAGAAGACGGCATACGAGATNNNNNNNNNXXXXXXXXGTGACTGGAGTTCAGACGTGT-3′
                  (rc_i7_5)                             (rc_i5_3 )

Forward Index Primer Sequence (i5)
   i5_5                                 i5_3
5′-AATGATACGGCGACCACCGAGATCTACACXXXXXXXXACACTCTTTCCCTACACGACGCTCTTCCGATCT-3′
                        (rc_i5_5)                                (rc_i5_3)

Reverse Index Primer Sequence (Ui7)
   ui7
5′-CAAGCAGAAGACGGCATACGA-3′
                (rc_ui7)
```

<details>
<summary> **Fasta** </summary>

```
>f (illumina foward adapter)
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
>b (illumina backward adapter)
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
>i7_5
CAAGCAGAAGACGGCATACGAGAT
>i7_3
GTGACTGGAGTTCAGACGTGT
>i5_5
AATGATACGGCGACCACCGAGATCTACAC
>i5_3
ACACTCTTTCCCTACACGACGCTCTTCCGATCT
>ui7
CAAGCAGAAGACGGCATACGA   
```
</details>


## Adapter Distribution

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(data.table)
library(ggplot2)
library(dplyr)
source("fn.r")
files <- list.files("../adapter", pattern = "\\.adapter$", full.names = TRUE)
p=plt_adapter(files);
md_save_pdf(p, "adapter.pdf", width = 12, height = 20); 

p=pl_summary("summary.tsv");
md_save_pdf(p, "summary.pdf", width = 12, height = 20); 

```



	
